export const HOME_PAGE_POSTS_LIMIT = 15;

export const DISCOVER_PAGE_POSTS_LIMIT = 15;

export const PEOPLE_PAGE_USERS_LIMIT = 15;

export const NOTIFICATIONS_PAGE_NOTIFICATION_LIMIT = 50;

export const MESSAGES_PAGE_MESSAGE_LIMIT = 50;

export const PROFILE_PAGE_POSTS_LIMIT = 15;
